// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/cache.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/cache.proto

It has these top-level messages:
	Empty
	GetRequest
	SetRequest
	FlushKeyRequest
	GetResponse
	SetResponse
	FlushResponse
	Result
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetRequest struct {
	Key    string  `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Result *Result `protobuf:"bytes,2,opt,name=Result" json:"Result,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetRequest) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type SetRequest struct {
	Key    string  `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Value  string  `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
	Result *Result `protobuf:"bytes,3,opt,name=Result" json:"Result,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetRequest) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type FlushKeyRequest struct {
	Key    string  `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Result *Result `protobuf:"bytes,2,opt,name=Result" json:"Result,omitempty"`
}

func (m *FlushKeyRequest) Reset()                    { *m = FlushKeyRequest{} }
func (m *FlushKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*FlushKeyRequest) ProtoMessage()               {}
func (*FlushKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FlushKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FlushKeyRequest) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetResponse struct {
	Value  string  `protobuf:"bytes,1,opt,name=Value" json:"Value,omitempty"`
	Result *Result `protobuf:"bytes,2,opt,name=Result" json:"Result,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type SetResponse struct {
	Result *Result `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *SetResponse) Reset()                    { *m = SetResponse{} }
func (m *SetResponse) String() string            { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()               {}
func (*SetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SetResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type FlushResponse struct {
	Result *Result `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *FlushResponse) Reset()                    { *m = FlushResponse{} }
func (m *FlushResponse) String() string            { return proto.CompactTextString(m) }
func (*FlushResponse) ProtoMessage()               {}
func (*FlushResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FlushResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type Result struct {
	Status string `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Result) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*SetRequest)(nil), "pb.SetRequest")
	proto.RegisterType((*FlushKeyRequest)(nil), "pb.FlushKeyRequest")
	proto.RegisterType((*GetResponse)(nil), "pb.GetResponse")
	proto.RegisterType((*SetResponse)(nil), "pb.SetResponse")
	proto.RegisterType((*FlushResponse)(nil), "pb.FlushResponse")
	proto.RegisterType((*Result)(nil), "pb.Result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cache service

type CacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	FlushAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FlushResponse, error)
	FlushKey(ctx context.Context, in *FlushKeyRequest, opts ...grpc.CallOption) (*FlushResponse, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/pb.Cache/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := grpc.Invoke(ctx, "/pb.Cache/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) FlushAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FlushResponse, error) {
	out := new(FlushResponse)
	err := grpc.Invoke(ctx, "/pb.Cache/FlushAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) FlushKey(ctx context.Context, in *FlushKeyRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	out := new(FlushResponse)
	err := grpc.Invoke(ctx, "/pb.Cache/FlushKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cache service

type CacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	FlushAll(context.Context, *Empty) (*FlushResponse, error)
	FlushKey(context.Context, *FlushKeyRequest) (*FlushResponse, error)
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cache/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_FlushAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).FlushAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cache/FlushAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).FlushAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_FlushKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).FlushKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cache/FlushKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).FlushKey(ctx, req.(*FlushKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Cache_Set_Handler,
		},
		{
			MethodName: "FlushAll",
			Handler:    _Cache_FlushAll_Handler,
		},
		{
			MethodName: "FlushKey",
			Handler:    _Cache_FlushKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/cache.proto",
}

func init() { proto.RegisterFile("pb/cache.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0xac, 0x1b, 0x25, 0xef, 0x65, 0x23, 0x5a, 0x30, 0x08, 0x55, 0x3d, 0x45, 0x3e, 0x45, 0x1c,
	0x82, 0x68, 0xf9, 0x01, 0x40, 0x90, 0x43, 0x6f, 0xb6, 0x84, 0xb8, 0x26, 0xd5, 0x4a, 0x3d, 0x18,
	0x62, 0xb0, 0x7d, 0xc8, 0xc7, 0xf1, 0x6f, 0xc8, 0x4e, 0xda, 0xb4, 0xa8, 0x41, 0x42, 0xdc, 0x76,
	0xbd, 0x33, 0xe3, 0x59, 0xcd, 0xc2, 0x44, 0x55, 0xd7, 0xeb, 0x72, 0xbd, 0xc1, 0x5c, 0x7d, 0xd4,
	0xa6, 0xa6, 0x63, 0x55, 0xb1, 0x7f, 0x10, 0x3e, 0xbe, 0x2a, 0xd3, 0xb0, 0x7b, 0x80, 0x02, 0x0d,
	0xc7, 0x77, 0x8b, 0xda, 0xd0, 0x53, 0x08, 0x56, 0xd8, 0xcc, 0x48, 0x4a, 0xb2, 0x98, 0xbb, 0x92,
	0x32, 0x88, 0x38, 0x6a, 0x2b, 0xcd, 0x6c, 0x9c, 0x92, 0x2c, 0x59, 0x40, 0xae, 0xaa, 0xbc, 0x7d,
	0xe1, 0xdd, 0x84, 0xbd, 0x00, 0x88, 0x9f, 0x34, 0x2e, 0x20, 0x7c, 0x2e, 0xa5, 0x45, 0x2f, 0x11,
	0xf3, 0xb6, 0xd9, 0x53, 0x0e, 0x06, 0x95, 0x0b, 0x98, 0x3e, 0x49, 0xab, 0x37, 0x2b, 0x6c, 0xfe,
	0x66, 0xb1, 0x80, 0xc4, 0xaf, 0xa9, 0x55, 0xfd, 0xa6, 0xb1, 0x77, 0x44, 0x8e, 0x3b, 0x1a, 0x16,
	0xba, 0x81, 0x44, 0xec, 0x09, 0xf5, 0x14, 0x32, 0x48, 0x59, 0xc2, 0x89, 0x5f, 0xe2, 0x57, 0xa4,
	0x74, 0x8b, 0xa1, 0x97, 0x10, 0x09, 0x53, 0x1a, 0xab, 0x3b, 0xb3, 0x5d, 0xb7, 0xf8, 0x24, 0x10,
	0x3e, 0xb8, 0x58, 0x69, 0x06, 0x41, 0x81, 0x86, 0x4e, 0x9c, 0x4c, 0x1f, 0xe6, 0x7c, 0xba, 0xeb,
	0xdb, 0x7f, 0xd9, 0xc8, 0x21, 0xc5, 0x16, 0x29, 0xbe, 0x21, 0xc5, 0x01, 0xf2, 0x0a, 0xfe, 0x7b,
	0xd3, 0x77, 0x52, 0xd2, 0xd8, 0x8d, 0xfd, 0xb9, 0xcc, 0xcf, 0x5c, 0x79, 0xb0, 0x0d, 0x1b, 0xd1,
	0xdb, 0x0e, 0xeb, 0xc2, 0x38, 0xdf, 0x01, 0xfa, 0xcc, 0x8e, 0xb2, 0xaa, 0xc8, 0x5f, 0xe3, 0xf2,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x9a, 0x00, 0x86, 0x9f, 0x02, 0x00, 0x00,
}
