// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/cache.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/cache.proto

It has these top-level messages:
	Empty
	GetRequest
	SetRequest
	FlushKeyRequest
	GetResponse
	GetAllResponse
	Result
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetRequest struct {
	Key string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type SetRequest struct {
	Key   string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type FlushKeyRequest struct {
	Key string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
}

func (m *FlushKeyRequest) Reset()                    { *m = FlushKeyRequest{} }
func (m *FlushKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*FlushKeyRequest) ProtoMessage()               {}
func (*FlushKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FlushKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Key   string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetAllResponse struct {
	GetResponse []*GetResponse `protobuf:"bytes,1,rep,name=GetResponse" json:"GetResponse,omitempty"`
}

func (m *GetAllResponse) Reset()                    { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()               {}
func (*GetAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetAllResponse) GetGetResponse() []*GetResponse {
	if m != nil {
		return m.GetResponse
	}
	return nil
}

type Result struct {
	Result string `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Result) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*SetRequest)(nil), "pb.SetRequest")
	proto.RegisterType((*FlushKeyRequest)(nil), "pb.FlushKeyRequest")
	proto.RegisterType((*GetResponse)(nil), "pb.GetResponse")
	proto.RegisterType((*GetAllResponse)(nil), "pb.GetAllResponse")
	proto.RegisterType((*Result)(nil), "pb.Result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cache service

type CacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Result, error)
	FlushAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error)
	FlushKey(ctx context.Context, in *FlushKeyRequest, opts ...grpc.CallOption) (*Result, error)
	Listener(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Cache_ListenerClient, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/pb.Cache/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := grpc.Invoke(ctx, "/pb.Cache/GetAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/pb.Cache/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) FlushAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/pb.Cache/FlushAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) FlushKey(ctx context.Context, in *FlushKeyRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/pb.Cache/FlushKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Listener(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Cache_ListenerClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cache_serviceDesc.Streams[0], c.cc, "/pb.Cache/Listener", opts...)
	if err != nil {
		return nil, err
	}
	x := &cacheListenerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cache_ListenerClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type cacheListenerClient struct {
	grpc.ClientStream
}

func (x *cacheListenerClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Cache service

type CacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetAll(context.Context, *Empty) (*GetAllResponse, error)
	Set(context.Context, *SetRequest) (*Result, error)
	FlushAll(context.Context, *Empty) (*Result, error)
	FlushKey(context.Context, *FlushKeyRequest) (*Result, error)
	Listener(*Empty, Cache_ListenerServer) error
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cache/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).GetAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cache/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_FlushAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).FlushAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cache/FlushAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).FlushAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_FlushKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).FlushKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cache/FlushKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).FlushKey(ctx, req.(*FlushKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Listener_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CacheServer).Listener(m, &cacheListenerServer{stream})
}

type Cache_ListenerServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type cacheListenerServer struct {
	grpc.ServerStream
}

func (x *cacheListenerServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Cache_GetAll_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Cache_Set_Handler,
		},
		{
			MethodName: "FlushAll",
			Handler:    _Cache_FlushAll_Handler,
		},
		{
			MethodName: "FlushKey",
			Handler:    _Cache_FlushKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listener",
			Handler:       _Cache_Listener_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/cache.proto",
}

func init() { proto.RegisterFile("pb/cache.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xbb, 0x0d, 0x89, 0xed, 0x14, 0x52, 0x19, 0x45, 0x42, 0x0e, 0x12, 0xb6, 0x08, 0xf1,
	0x60, 0xd4, 0xaa, 0x1f, 0x40, 0x8a, 0xe6, 0x50, 0x4f, 0x29, 0x78, 0x6f, 0xca, 0x40, 0x85, 0xb5,
	0x59, 0xbb, 0x9b, 0x43, 0xbe, 0xbb, 0x07, 0xd9, 0x4d, 0x5a, 0xd3, 0x40, 0xc5, 0xdb, 0xfc, 0x79,
	0xf9, 0xcd, 0xcb, 0x63, 0xc1, 0x97, 0xf9, 0xed, 0x6a, 0xb9, 0x5a, 0x53, 0x22, 0xb7, 0x85, 0x2e,
	0xb0, 0x2f, 0x73, 0x7e, 0x02, 0xee, 0xcb, 0xa7, 0xd4, 0x15, 0xbf, 0x04, 0x48, 0x49, 0x67, 0xf4,
	0x55, 0x92, 0xd2, 0x78, 0x0a, 0xce, 0x9c, 0xaa, 0x80, 0x45, 0x2c, 0x1e, 0x66, 0xa6, 0xe4, 0x8f,
	0x00, 0x8b, 0x3f, 0xf6, 0x78, 0x0e, 0xee, 0xfb, 0x52, 0x94, 0x14, 0xf4, 0xed, 0xac, 0x6e, 0xf8,
	0x04, 0xc6, 0xaf, 0xa2, 0x54, 0xeb, 0x39, 0x55, 0xc7, 0xd1, 0x4f, 0x30, 0xb2, 0xa7, 0x95, 0x2c,
	0x36, 0x8a, 0xfe, 0xcd, 0x9e, 0x81, 0x9f, 0x92, 0x7e, 0x16, 0x62, 0xff, 0xe5, 0xfd, 0x01, 0x28,
	0x60, 0x91, 0x13, 0x8f, 0xa6, 0xe3, 0x44, 0xe6, 0x49, 0x6b, 0x9c, 0xb5, 0x35, 0x3c, 0x02, 0x2f,
	0x23, 0x55, 0x0a, 0x8d, 0x17, 0xbb, 0xaa, 0xb9, 0xdc, 0x74, 0xd3, 0x6f, 0x06, 0xee, 0xcc, 0xa4,
	0x86, 0x31, 0x38, 0x29, 0x69, 0xf4, 0xf7, 0x40, 0xfb, 0x43, 0x61, 0xf7, 0x00, 0xef, 0xe1, 0x35,
	0x78, 0xb5, 0x35, 0x1c, 0x9a, 0xa5, 0x4d, 0x38, 0xc4, 0x46, 0xd7, 0x72, 0xcc, 0x7b, 0x38, 0x01,
	0x67, 0xb1, 0x83, 0xfe, 0x06, 0x1c, 0x82, 0xe9, 0x6b, 0x07, 0x56, 0x34, 0xb0, 0x31, 0x76, 0x88,
	0x87, 0xa2, 0x9b, 0x46, 0x64, 0x12, 0x3b, 0x33, 0x9b, 0x4e, 0xf2, 0x1d, 0xf9, 0x15, 0x0c, 0xde,
	0x3e, 0x94, 0xa6, 0x0d, 0x6d, 0x8f, 0x32, 0xef, 0x58, 0xee, 0xd9, 0xb7, 0xf2, 0xf0, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x6a, 0x91, 0x99, 0x84, 0x3d, 0x02, 0x00, 0x00,
}
